# Generated by Django 4.2 on 2025-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
